#!/bin/bash

find /media/Main/Movies -maxdepth 1 -type d -printf '%f\n' > ~/Backups/movies.txt
find /media/Main/TV -maxdepth 1 -type d -printf '%f\n' > ~/Backups/tvs.txt
find /media/Main/Music -maxdepth 1 -type d -printf '%f\n' > ~/Backups/musics.txt
